### ISSUE TITLE
How do you implement TD3 with TOP?

### ISSUE THREAD

**Issue by kbkartik** [tedmoskovitz/TOP#2]
Hi Ted,

1. I like your work on TOP. The current Git code seems to be the TOP version without TD3. How do you implement TOP-TD3?
2. What seed values do you use for evaluations?

Thanks,
kb

**Comment by tedmoskovitz** [comment]
Hi KB, 

1. Glad that you like TOP! TOP-TD3 should be implemented here: https://github.com/tedmoskovitz/TOP/blob/master/mujoco/top.py. 
2. Unfortunately, I didn't save the specific seeds. 

Best,
Ted

**Comment by kbkartik** [comment]
Hi Ted,

Thanks for the quick response. Isn't https://github.com/tedmoskovitz/TOP/blob/master/mujoco/top.py just the TOP version w/o TD3? Where do you minimize over the two target networks like the TD3 algorithm?

**Comment by tedmoskovitz** [comment]
Ah, so in TOP-TD3 we replace the minimization over the target networks with the belief distribution formed by mean + beta * sigma (where beta can be negative and is sampled from the bandit algorithm) as described in Section 5 of the paper. Hope that's helpful!
